# Generated by Django 3.0 on 2021-07-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecommerce',
            new_name='Additem',
        ),
    ]
