# Generated by Django 3.0 on 2021-07-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_itemlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='itavailability',
            field=models.CharField(choices=[('AV', 'available'), ('NA', 'not available')], default='none', max_length=20),
        ),
    ]
