# Generated by Django 3.0 on 2021-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20210731_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='itavailability',
            field=models.CharField(choices=[('AV', 'available'), ('NA', 'not available'), ('DF', 'Select availability')], default='DF', max_length=20),
        ),
    ]
