# Generated by Django 3.0 on 2021-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20210731_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
